# Uses https://github.com/marketplace/actions/lintly-flake8?version=v1.0
name: Python Style (PR)

on:
  pull_request:
    branches: [ master ]

jobs:
  check-style:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Lintly-Flake8
        uses: grantmcconnaughey/lintly-flake8-github-action@v1.0
        with:
          # The GitHub API token to create reviews with
          token: ${{ secrets.GITHUB_TOKEN }}